// apps/task-manager-backoffice/src/app/shared/components/ui/badge/badge.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import { CommonModule } from '@angular/common';

export type BadgeVariant =
  | 'default'
  | 'primary'
  | 'success'
  | 'warning'
  | 'danger'
  | 'info'
  | 'neutral'
  | 'purple';

export type BadgeSize = 'sm' | 'md';

@Component({
  selector: 'app-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span [class]="badgeClasses()">
      @if (dot()) {
        <span
          class="w-1.5 h-1.5 rounded-full"
          [class]="dotClasses()"
          [class.animate-pulse]="pulse()"
          aria-hidden="true"
        ></span>
      }
      <ng-content />
    </span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BadgeComponent {
  readonly variant = input<BadgeVariant>('default');
  readonly size = input<BadgeSize>('sm');
  readonly dot = input<boolean>(false);
  readonly pulse = input<boolean>(false);
  readonly customClass = input<string>('');

  protected readonly badgeClasses = computed(() => {
    const base =
      'inline-flex items-center gap-1.5 font-medium rounded-full border select-none';

    const sizes: Record<BadgeSize, string> = {
      sm: 'text-[11px] px-2.5 py-0.5',
      md: 'text-xs px-3 py-1',
    };

    const variants: Record<BadgeVariant, string> = {
      default: 'bg-slate-800/80 text-slate-300 border-slate-700/80',
      primary: 'bg-indigo-500/15 text-indigo-400 border-indigo-500/30',
      success: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
      warning: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
      danger: 'bg-rose-500/15 text-rose-400 border-rose-500/30',
      info: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
      purple: 'bg-purple-500/15 text-purple-400 border-purple-500/30',
      neutral: 'bg-slate-500/15 text-slate-300 border-slate-600/40',
    };

    return `${base} ${sizes[this.size()]} ${variants[this.variant()]} ${this.customClass()}`.trim();
  });

  protected readonly dotClasses = computed(() => {
    const dotColors: Record<BadgeVariant, string> = {
      default: 'bg-slate-400',
      primary: 'bg-indigo-400',
      success: 'bg-emerald-400',
      warning: 'bg-amber-400',
      danger: 'bg-rose-400',
      info: 'bg-cyan-400',
      purple: 'bg-purple-400',
      neutral: 'bg-slate-400',
    };

    return dotColors[this.variant()] || 'bg-slate-400';
  });
}

// task-manager-client/src/shared/components/ui/badge/index.tsx
import React from 'react';
import { cn } from '@shared/utils/cn';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'purple' | 'amber' | 'emerald' | 'slate' | 'red';
  size?: 'sm' | 'md';
  icon?: React.ReactNode;
}

export const Badge: React.FC<BadgeProps> = ({
  children,
  className,
  variant = 'purple',
  size = 'md',
  icon,
  ...props
}) => {
  const baseStyles = 'inline-flex items-center font-semibold rounded-full border';

  const variants = {
    purple:
      'bg-purple-100 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800',
    amber:
      'bg-amber-100 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800',
    emerald:
      'bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
    slate:
      'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-700',
    red:
      'bg-red-100 dark:bg-red-950/60 text-red-700 dark:text-red-300 border-red-200 dark:border-red-800',
  };

  const sizes = {
    sm: 'px-2 py-0.5 text-[10px] gap-1',
    md: 'px-2.5 py-1 text-xs gap-1.5',
  };

  return (
    <span className={cn(baseStyles, variants[variant], sizes[size], className)} {...props}>
      {icon}
      {children}
    </span>
  );
};
