// task-manager-backoffice/src/app/shared/components/ui/pagination/pagination.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="px-6 py-4 bg-slate-950/60 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4"
    >
      <div class="text-xs text-slate-400">
        Mostrando
        <span class="font-semibold text-white"
          >{{ fromIndex() }} - {{ toIndex() }}</span
        >
        de <span class="font-semibold text-white">{{ totalItems() }}</span>
        {{ itemLabel() }}
      </div>

      <div class="flex items-center gap-1.5">
        <button
          type="button"
          [disabled]="currentPage() <= 1"
          (click)="goToPage(currentPage() - 1)"
          class="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-slate-900 disabled:hover:text-slate-400 text-xs transition-colors cursor-pointer"
        >
          Anterior
        </button>

        @for (p of pages(); track p) {
          <button
            type="button"
            (click)="goToPage(p)"
            [class]="
              p === currentPage()
                ? 'bg-indigo-600 text-white font-semibold shadow-xs'
                : 'bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800'
            "
            class="px-3 py-1.5 rounded-lg text-xs transition-colors cursor-pointer"
          >
            {{ p }}
          </button>
        }

        <button
          type="button"
          [disabled]="currentPage() >= totalPages()"
          (click)="goToPage(currentPage() + 1)"
          class="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-slate-900 disabled:hover:text-slate-400 text-xs transition-colors cursor-pointer"
        >
          Siguiente
        </button>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationComponent {
  readonly currentPage = input<number>(1);
  readonly totalItems = input<number>(0);
  readonly itemsPerPage = input<number>(10);
  readonly itemLabel = input<string>('elementos');

  readonly pageChange = output<number>();

  protected readonly totalPages = computed(() => {
    const total = this.totalItems();
    const perPage = this.itemsPerPage() || 1;
    return Math.max(1, Math.ceil(total / perPage));
  });

  protected readonly fromIndex = computed(() => {
    if (this.totalItems() === 0) return 0;
    return (this.currentPage() - 1) * this.itemsPerPage() + 1;
  });

  protected readonly toIndex = computed(() => {
    return Math.min(
      this.currentPage() * this.itemsPerPage(),
      this.totalItems(),
    );
  });

  protected readonly pages = computed(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    const pageList: number[] = [];
    const maxVisible = 5;

    let start = Math.max(1, current - Math.floor(maxVisible / 2));
    const end = Math.min(total, start + maxVisible - 1);

    if (end - start + 1 < maxVisible) {
      start = Math.max(1, end - maxVisible + 1);
    }

    for (let i = start; i <= end; i++) {
      pageList.push(i);
    }

    return pageList;
  });

  protected goToPage(page: number): void {
    if (page >= 1 && page <= this.totalPages() && page !== this.currentPage()) {
      this.pageChange.emit(page);
    }
  }
}

// task-manager-client/src/shared/components/ui/table/components/pagination/index.tsx
import React from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import useTablePagination from './hooks';

interface Props {
  currentPage: number;
  totalPages: number;
  totalItems: number;
  itemsPerPage: number;
  onPageChange: (page: number) => void;
}

export const TablePagination: React.FC<Props> = ({
  currentPage,
  totalPages,
  totalItems,
  itemsPerPage,
  onPageChange,
}) => {
  const { startItem, endItem, visiblePages, isFirstPage, isLastPage } = useTablePagination({
    totalItems,
    currentPage,
    totalPages,
    itemsPerPage,
  });

  return (
    <div className="px-4 sm:px-6 py-3.5 bg-slate-50/60 dark:bg-slate-900/30 border-t border-slate-200/80 dark:border-slate-700/80 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
      <div>
        Mostrando{' '}
        <span className="font-semibold text-slate-700 dark:text-slate-200">{startItem}</span> a{' '}
        <span className="font-semibold text-slate-700 dark:text-slate-200">{endItem}</span> de{' '}
        <span className="font-semibold text-slate-700 dark:text-slate-200">{totalItems}</span>{' '}
        resultados
      </div>

      <div className="flex items-center gap-2">
        <button
          aria-label="Anterior"
          onClick={() => onPageChange(currentPage - 1)}
          disabled={isFirstPage}
          className="p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 disabled:opacity-40 disabled:cursor-not-allowed hover:enabled:bg-slate-50 dark:hover:enabled:bg-slate-700 transition-colors cursor-pointer"
        >
          <ChevronLeft className="w-4 h-4" />
        </button>

        {visiblePages.map((page) => (
          <button
            key={page}
            onClick={() => onPageChange(page)}
            className={`w-7 h-7 rounded-lg text-xs font-semibold flex items-center justify-center transition-all cursor-pointer ${
              page === currentPage
                ? 'bg-purple-500 text-white shadow-xs'
                : 'border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700'
            }`}
          >
            {page}
          </button>
        ))}

        <button
          aria-label="Siguiente"
          onClick={() => onPageChange(currentPage + 1)}
          disabled={isLastPage}
          className="p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 disabled:opacity-40 disabled:cursor-not-allowed hover:enabled:bg-slate-50 dark:hover:enabled:bg-slate-700 transition-colors cursor-pointer"
        >
          <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
};
